services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - '8000:8000'
    command: '-jar DynamoDBLocal.jar -sharedDb'
    volumes:
      - ./dynamo_data:/home/dynamodblocal/data
    restart: unless-stopped
